// appShell.jsx — generic NeuroRAN console shell (rail + topbar + active tab)
// Exposes (global + window): App
//
// This file is rApp-agnostic. It reads window.RAPP_CONFIG and renders:
//   - a left rail built from config.tabs
//   - a topbar (crumb + site badge + clock + dark toggle)
//   - the active tab's component, looked up by name on window
// Each tab component is called as <Comp state colors config actions t setTweak />.
// Do not edit this file to add screens or KPIs — edit rapp.config.jsx and src/tabs/.

const { useState, useEffect, useMemo } = React;

function SiteClock({ tz }) {
  const [now, setNow] = useState(() => fmtSiteNow(tz));
  useEffect(() => {
    const id = setInterval(() => setNow(fmtSiteNow(tz)), 1000);
    return () => clearInterval(id);
  }, [tz]);
  return (
    <span className="clock" title={tz}>
      <span className="status-dot dot-ok" />
      {now}
    </span>
  );
}

const Rail = React.memo(function Rail({ tabs, tab, setTab, brand }) {
  return (
    <aside className="rail">
      <div className="rail-brand" title={brand.title}>
        <picture>
          {brand.logoPng && <source srcSet={brand.logoPng} type="image/png" />}
          <img className="rail-logo" src={brand.logo} alt={brand.product} />
        </picture>
      </div>

      <nav className="rail-nav" aria-label="Main navigation">
        {tabs.map(({ id, label, icon }) => (
          <button
            key={id}
            type="button"
            className={"rail-tab" + (tab === id ? " rail-tab-active" : "")}
            onClick={() => setTab(id)}
            aria-current={tab === id ? "page" : undefined}
          >
            <span className="rail-tab-icon">{icon}</span>
            <span className="rail-tab-label">{label}</span>
          </button>
        ))}
      </nav>

      <div className="rail-foot">
        <div className="rail-status" title={brand.shortName + " · Healthy"}>
          <span className="rail-status-dot" />
          <span className="rail-status-text">{brand.shortName}</span>
        </div>
      </div>
    </aside>
  );
});

function DarkToggle({ dark, onToggle }) {
  return (
    <button
      type="button"
      className="icon-btn icon-btn-sq"
      onClick={onToggle}
      title={dark ? "Switch to light mode" : "Switch to dark mode"}
      aria-label={dark ? "Switch to light mode" : "Switch to dark mode"}
    >
      {dark ? (
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
          <circle cx="12" cy="12" r="4" />
          <path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41" />
        </svg>
      ) : (
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
          <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
        </svg>
      )}
    </button>
  );
}

function App() {
  const config = window.RAPP_CONFIG;
  const tabs = config.tabs || [];
  const tweakDefaults = useMemo(() => ({
    dark: !!config.theme?.dark,
    accent: config.theme?.accent || "Energy green",
    density: config.theme?.density || "comfy",
  }), []);

  const [t, setTweak] = useTweaks(tweakDefaults);
  // UI-only scaffold: screens render from static example data in the config.
  // Preview only — static exampleState. Real data wiring is out of scope for this skill.
  const [state, setState] = useState(() => config.exampleState || {});
  const [tab, setTab] = useState(tabs[0]?.id);

  const colors = useMemo(() => buildColors(t.dark, t.accent), [t.dark, t.accent]);

  // Local-only helpers for tabs (e.g. profile selection via setState).
  const actions = useMemo(() => ({
    setState,
    goToTab: setTab,
  }), []);

  const activeTab = tabs.find((x) => x.id === tab) || tabs[0];
  const TabComp = activeTab ? window[activeTab.component] : null;

  const appClass = "app " + (t.dark ? "theme-dark" : "theme-light") + " density-" + t.density;
  const appVars = {
    "--accent": colors.accent, "--accent2": colors.accent2,
    "--accent-glow": colors.accentGlow, "--bad": colors.bad,
  };

  return (
    <div className={appClass} style={appVars}>
      <Rail tabs={tabs} tab={tab} setTab={setTab} brand={config.brand} />

      <div className="app-body">
        <div className="main-col">
          <header className="topbar">
            <div className="crumb">{activeTab?.label || config.brand.title}</div>
            {config.site?.label && <span className="site-badge">{config.site.label}</span>}
            <div className="topbar-right">
              <SiteClock tz={config.site?.clockTz} />
              <DarkToggle dark={t.dark} onToggle={() => setTweak("dark", !t.dark)} />
            </div>
          </header>

          <main className="dash">
            {TabComp
              ? <TabComp state={state} colors={colors} config={config} actions={actions} t={t} setTweak={setTweak} />
              : <div className="card">Tab component "{activeTab?.component}" is not registered. Check src/tabs and index.html script order.</div>}
          </main>
        </div>
      </div>

      <TweaksPanel>
        <TweakSection label="Appearance" />
        <TweakToggle label="Dark mode" value={t.dark} onChange={(v) => setTweak("dark", v)} />
        <TweakSelect label="Accent" value={t.accent} options={Object.keys(ACCENTS)} onChange={(v) => setTweak("accent", v)} />
        <TweakRadio label="Density" value={t.density} options={["compact", "comfy"]} onChange={(v) => setTweak("density", v)} />
      </TweaksPanel>
    </div>
  );
}

Object.assign(window, { App });
